

--CREACION DE TABLAS
CREATE TABLE USUARIO(
id_usuario int NOT NULL,
nombre_usuario varchar2(30) NOT NULL,
clave varchar2(30) NOT NULL,
tipo_usuario varchar2(30) NOT NULL,
funcionario_run_sin_dv int NOT NULL
);

CREATE TABLE FUNCIONARIO(
run_sin_dv int NOT NULL,
run_dv int NOT NULL,
nom_funcionario varchar2(30) NOT NULL,
ap_paterno varchar2(30) NOT NULL,
ap_materno varchar2(30) NOT NULL,
fec_nacimiento date NOT NULL,
correo varchar2(100) NOT NULL,
direc_funcionario varchar2(80) NOT NULL,
tipo_funcionario varchar2(30) NOT NULL,
habilitado number(1) NOT NULL,
unidad_id_unidad int NOT NULL
);


CREATE TABLE SOL_PERMISO(
id_permiso int NOT NULL,
tipo_permiso varchar2(30) NOT NULL,
estado int,
fecha_inicio date NOT NULL,
fecha_termino date NOT NULL,
fecha_solicitud date NOT NULL,
desc_permiso varchar2(254) NOT NULL,
solicitante_run_sin_dv int NOT NULL,
autorizante_run_sin_dv int
);

CREATE TABLE RESOLUCION(
id_resolucion int NOT NULL,
fec_resolucion date NOT NULL,
estado_resolucion int,
permiso_id_permiso int NOT NULL,
resolvente_run_sin_dv int
);

CREATE TABLE DOCUMENTO(
id_documento int NOT NULL,
nombre_documento varchar2(30) NOT NULL,
formato_documento varchar2(20) NOT NULL,
fec_creacion date NOT NULL,
directorio_documento varchar2(254) NOT NULL,
permiso_id_permiso int NOT NULL
);

CREATE TABLE UNIDAD(
id_unidad int NOT NULL,
nombre_unidad varchar2(30) NOT NULL,
descripcion_unidad varchar2(254) NOT NULL,
direccion_unidad varchar2(80) NOT NULL,
habilitado number(1) NOT NULL,
unidad_padre_id_unidad int,
jefe_unidad_run_sin_dv int
);

--GENERACION DE CONSTRAINTS

--CLAVES PRIMARIAS
ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY(id_usuario);
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(run_sin_dv);
ALTER TABLE SOL_PERMISO
ADD CONSTRAINT PK_SOL_PERMISO PRIMARY KEY(id_permiso);
ALTER TABLE RESOLUCION
ADD CONSTRAINT PK_RESOLUCION PRIMARY KEY(id_resolucion);
ALTER TABLE DOCUMENTO
ADD CONSTRAINT PK_DOCUMENTO PRIMARY KEY(id_documento);
ALTER TABLE UNIDAD
ADD CONSTRAINT PK_UNIDAD PRIMARY KEY(id_unidad);


--CLAVES FORANEAS
ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_FUNCIONARIO FOREIGN KEY(funcionario_run_sin_dv) REFERENCES FUNCIONARIO(run_sin_dv);
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_UNIDAD FOREIGN KEY(unidad_id_unidad) REFERENCES UNIDAD(id_unidad);
ALTER TABLE SOL_PERMISO
ADD CONSTRAINT FK_PERMISO_SOLICITANTE FOREIGN KEY(solicitante_run_sin_dv) REFERENCES FUNCIONARIO(run_sin_dv);
ALTER TABLE SOL_PERMISO
ADD CONSTRAINT FK_PERMISO_AUTORIZANTE FOREIGN KEY(autorizante_run_sin_dv) REFERENCES FUNCIONARIO(run_sin_dv);
ALTER TABLE RESOLUCION
ADD CONSTRAINT FK_RESOLUCION_RESOLVENTE FOREIGN KEY(resolvente_run_sin_dv) REFERENCES FUNCIONARIO(run_sin_dv);
ALTER TABLE RESOLUCION
ADD CONSTRAINT FK_RESOLUCION_PERMISO FOREIGN KEY(permiso_id_permiso) REFERENCES SOL_PERMISO(id_permiso);
ALTER TABLE DOCUMENTO
ADD CONSTRAINT FK_DOCUMENTO_PERMISO FOREIGN KEY(permiso_id_permiso) REFERENCES SOL_PERMISO(id_permiso);
ALTER TABLE UNIDAD
ADD CONSTRAINT FK_UNIDAD_JEFE FOREIGN KEY(jefe_unidad_run_sin_dv) REFERENCES FUNCIONARIO(run_sin_dv);
ALTER TABLE UNIDAD
ADD CONSTRAINT FK_UNIDAD_UNIDADPADRE FOREIGN KEY(unidad_padre_id_unidad) REFERENCES UNIDAD(id_unidad);

--CAMPOS UNICOS
ALTER TABLE USUARIO
ADD CONSTRAINT UNQ_NOMBRE_USUARIO UNIQUE(nombre_usuario);
ALTER TABLE UNIDAD
ADD CONSTRAINT UNQ_NOMBRE_UNIDAD UNIQUE(nombre_unidad);
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT UNQ_CORREO UNIQUE(correo);

-- SEEDS
INSERT INTO PRUEBA.UNIDAD(ID_UNIDAD,NOMBRE_UNIDAD,DESCRIPCION_UNIDAD,DIRECCION_UNIDAD,HABILITADO) VALUES (PRUEBA.UNIDAD_SEQ.NEXTVAL,'Unidad Primera','Es la mejor unidad','av. antonio varas 666',1);
INSERT INTO PRUEBA.FUNCIONARIO VALUES (1,9,'Ad','min','istrador',sysdate,'admin@vistahermosa.cl','av. antonio varas 666','administrador',1,1);
INSERT INTO PRUEBA.FUNCIONARIO VALUES (16976780,7,'Gabo','Jara','Soto',sysdate,'g.jaras@alumnos.duoc.cl','av. antonio varas 666','asistente contador',1,1);
INSERT INTO PRUEBA.USUARIO VALUES (PRUEBA.USUARIO_SEQ.NEXTVAL,'admin','pass','admin',1);

-- SECUENCIAS

CREATE SEQUENCE  "PRUEBA"."USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE  "PRUEBA"."SOL_PERMISOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE  "PRUEBA"."RESOLUCION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE  "PRUEBA"."DOCUMENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE  "PRUEBA"."UNIDAD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOCYCLE ;



