package com.gjaras.pojos;
// Generated Oct 3, 2018 5:29:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private BigDecimal idDocumento;
     private SolPermiso solPermiso;
     private String nombreDocumento;
     private String formatoDocumento;
     private Date fecCreacion;
     private String directorioDocumento;

    public Documento() {
    }

    public Documento(BigDecimal idDocumento, SolPermiso solPermiso, String nombreDocumento, String formatoDocumento, Date fecCreacion, String directorioDocumento) {
       this.idDocumento = idDocumento;
       this.solPermiso = solPermiso;
       this.nombreDocumento = nombreDocumento;
       this.formatoDocumento = formatoDocumento;
       this.fecCreacion = fecCreacion;
       this.directorioDocumento = directorioDocumento;
    }
   
    public BigDecimal getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(BigDecimal idDocumento) {
        this.idDocumento = idDocumento;
    }
    public SolPermiso getSolPermiso() {
        return this.solPermiso;
    }
    
    public void setSolPermiso(SolPermiso solPermiso) {
        this.solPermiso = solPermiso;
    }
    public String getNombreDocumento() {
        return this.nombreDocumento;
    }
    
    public void setNombreDocumento(String nombreDocumento) {
        this.nombreDocumento = nombreDocumento;
    }
    public String getFormatoDocumento() {
        return this.formatoDocumento;
    }
    
    public void setFormatoDocumento(String formatoDocumento) {
        this.formatoDocumento = formatoDocumento;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getDirectorioDocumento() {
        return this.directorioDocumento;
    }
    
    public void setDirectorioDocumento(String directorioDocumento) {
        this.directorioDocumento = directorioDocumento;
    }




}


