package com.gjaras.pojos;
// Generated Oct 3, 2018 5:29:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private BigDecimal runSinDv;
     private Unidad unidad;
     private BigDecimal runDv;
     private String nomFuncionario;
     private String apPaterno;
     private String apMaterno;
     private Date fecNacimiento;
     private String correo;
     private String direcFuncionario;
     private String tipoFuncionario;
     private boolean habilitado;
     private Set usuarios = new HashSet(0);
     private Set resolucions = new HashSet(0);
     private Set solPermisosForAutorizanteRunSinDv = new HashSet(0);
     private Set solPermisosForSolicitanteRunSinDv = new HashSet(0);
     private Set unidads = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(BigDecimal runSinDv, Unidad unidad, BigDecimal runDv, String nomFuncionario, String apPaterno, String apMaterno, Date fecNacimiento, String correo, String direcFuncionario, String tipoFuncionario, boolean habilitado) {
        this.runSinDv = runSinDv;
        this.unidad = unidad;
        this.runDv = runDv;
        this.nomFuncionario = nomFuncionario;
        this.apPaterno = apPaterno;
        this.apMaterno = apMaterno;
        this.fecNacimiento = fecNacimiento;
        this.correo = correo;
        this.direcFuncionario = direcFuncionario;
        this.tipoFuncionario = tipoFuncionario;
        this.habilitado = habilitado;
    }
    public Funcionario(BigDecimal runSinDv, Unidad unidad, BigDecimal runDv, String nomFuncionario, String apPaterno, String apMaterno, Date fecNacimiento, String correo, String direcFuncionario, String tipoFuncionario, boolean habilitado, Set usuarios, Set resolucions, Set solPermisosForAutorizanteRunSinDv, Set solPermisosForSolicitanteRunSinDv, Set unidads) {
       this.runSinDv = runSinDv;
       this.unidad = unidad;
       this.runDv = runDv;
       this.nomFuncionario = nomFuncionario;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.fecNacimiento = fecNacimiento;
       this.correo = correo;
       this.direcFuncionario = direcFuncionario;
       this.tipoFuncionario = tipoFuncionario;
       this.habilitado = habilitado;
       this.usuarios = usuarios;
       this.resolucions = resolucions;
       this.solPermisosForAutorizanteRunSinDv = solPermisosForAutorizanteRunSinDv;
       this.solPermisosForSolicitanteRunSinDv = solPermisosForSolicitanteRunSinDv;
       this.unidads = unidads;
    }
   
    public BigDecimal getRunSinDv() {
        return this.runSinDv;
    }
    
    public void setRunSinDv(BigDecimal runSinDv) {
        this.runSinDv = runSinDv;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getRunDv() {
        return this.runDv;
    }
    
    public void setRunDv(BigDecimal runDv) {
        this.runDv = runDv;
    }
    public String getNomFuncionario() {
        return this.nomFuncionario;
    }
    
    public void setNomFuncionario(String nomFuncionario) {
        this.nomFuncionario = nomFuncionario;
    }
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDirecFuncionario() {
        return this.direcFuncionario;
    }
    
    public void setDirecFuncionario(String direcFuncionario) {
        this.direcFuncionario = direcFuncionario;
    }
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }
    public Set getSolPermisosForAutorizanteRunSinDv() {
        return this.solPermisosForAutorizanteRunSinDv;
    }
    
    public void setSolPermisosForAutorizanteRunSinDv(Set solPermisosForAutorizanteRunSinDv) {
        this.solPermisosForAutorizanteRunSinDv = solPermisosForAutorizanteRunSinDv;
    }
    public Set getSolPermisosForSolicitanteRunSinDv() {
        return this.solPermisosForSolicitanteRunSinDv;
    }
    
    public void setSolPermisosForSolicitanteRunSinDv(Set solPermisosForSolicitanteRunSinDv) {
        this.solPermisosForSolicitanteRunSinDv = solPermisosForSolicitanteRunSinDv;
    }
    public Set getUnidads() {
        return this.unidads;
    }
    
    public void setUnidads(Set unidads) {
        this.unidads = unidads;
    }
    public String toString(){
        StringBuilder sb = new StringBuilder();
        sb.append("Funcionario: \n");
        sb.append(" Rut: "+getRunSinDv()+"-"+getRunDv()+"\n");
        sb.append(" Nombre: "+getNomFuncionario()+" "+getApPaterno()+""+getApMaterno()+"\n");
        return sb.toString();
    }
}


