package com.gjaras.pojos;
// Generated Oct 3, 2018 5:29:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Resolucion generated by hbm2java
 */
public class Resolucion  implements java.io.Serializable {


     private BigDecimal idResolucion;
     private Funcionario funcionario;
     private SolPermiso solPermiso;
     private Date fecResolucion;
     private BigDecimal estadoResolucion;

    public Resolucion() {
    }

	
    public Resolucion(BigDecimal idResolucion, SolPermiso solPermiso, Date fecResolucion) {
        this.idResolucion = idResolucion;
        this.solPermiso = solPermiso;
        this.fecResolucion = fecResolucion;
    }
    public Resolucion(BigDecimal idResolucion, Funcionario funcionario, SolPermiso solPermiso, Date fecResolucion, BigDecimal estadoResolucion) {
       this.idResolucion = idResolucion;
       this.funcionario = funcionario;
       this.solPermiso = solPermiso;
       this.fecResolucion = fecResolucion;
       this.estadoResolucion = estadoResolucion;
    }
   
    public BigDecimal getIdResolucion() {
        return this.idResolucion;
    }
    
    public void setIdResolucion(BigDecimal idResolucion) {
        this.idResolucion = idResolucion;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public SolPermiso getSolPermiso() {
        return this.solPermiso;
    }
    
    public void setSolPermiso(SolPermiso solPermiso) {
        this.solPermiso = solPermiso;
    }
    public Date getFecResolucion() {
        return this.fecResolucion;
    }
    
    public void setFecResolucion(Date fecResolucion) {
        this.fecResolucion = fecResolucion;
    }
    public BigDecimal getEstadoResolucion() {
        return this.estadoResolucion;
    }
    
    public void setEstadoResolucion(BigDecimal estadoResolucion) {
        this.estadoResolucion = estadoResolucion;
    }




}


