package com.gjaras.pojos;
// Generated Oct 3, 2018 5:29:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolPermiso generated by hbm2java
 */
public class SolPermiso  implements java.io.Serializable {


     private BigDecimal idPermiso;
     private Funcionario funcionarioByAutorizanteRunSinDv;
     private Funcionario funcionarioBySolicitanteRunSinDv;
     private String tipoPermiso;
     private BigDecimal estado;
     private Date fechaInicio;
     private Date fechaTermino;
     private Date fechaSolicitud;
     private String descPermiso;
     private Set resolucions = new HashSet(0);
     private Set documentos = new HashSet(0);

    public SolPermiso() {
    }

	
    public SolPermiso(BigDecimal idPermiso, Funcionario funcionarioBySolicitanteRunSinDv, String tipoPermiso, Date fechaInicio, Date fechaTermino, Date fechaSolicitud, String descPermiso) {
        this.idPermiso = idPermiso;
        this.funcionarioBySolicitanteRunSinDv = funcionarioBySolicitanteRunSinDv;
        this.tipoPermiso = tipoPermiso;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
        this.fechaSolicitud = fechaSolicitud;
        this.descPermiso = descPermiso;
    }
    public SolPermiso(BigDecimal idPermiso, Funcionario funcionarioByAutorizanteRunSinDv, Funcionario funcionarioBySolicitanteRunSinDv, String tipoPermiso, BigDecimal estado, Date fechaInicio, Date fechaTermino, Date fechaSolicitud, String descPermiso, Set resolucions, Set documentos) {
       this.idPermiso = idPermiso;
       this.funcionarioByAutorizanteRunSinDv = funcionarioByAutorizanteRunSinDv;
       this.funcionarioBySolicitanteRunSinDv = funcionarioBySolicitanteRunSinDv;
       this.tipoPermiso = tipoPermiso;
       this.estado = estado;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.fechaSolicitud = fechaSolicitud;
       this.descPermiso = descPermiso;
       this.resolucions = resolucions;
       this.documentos = documentos;
    }
   
    public BigDecimal getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(BigDecimal idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Funcionario getFuncionarioByAutorizanteRunSinDv() {
        return this.funcionarioByAutorizanteRunSinDv;
    }
    
    public void setFuncionarioByAutorizanteRunSinDv(Funcionario funcionarioByAutorizanteRunSinDv) {
        this.funcionarioByAutorizanteRunSinDv = funcionarioByAutorizanteRunSinDv;
    }
    public Funcionario getFuncionarioBySolicitanteRunSinDv() {
        return this.funcionarioBySolicitanteRunSinDv;
    }
    
    public void setFuncionarioBySolicitanteRunSinDv(Funcionario funcionarioBySolicitanteRunSinDv) {
        this.funcionarioBySolicitanteRunSinDv = funcionarioBySolicitanteRunSinDv;
    }
    public String getTipoPermiso() {
        return this.tipoPermiso;
    }
    
    public void setTipoPermiso(String tipoPermiso) {
        this.tipoPermiso = tipoPermiso;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public String getDescPermiso() {
        return this.descPermiso;
    }
    
    public void setDescPermiso(String descPermiso) {
        this.descPermiso = descPermiso;
    }
    public Set getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


