package com.gjaras.pojos;
// Generated Oct 3, 2018 5:29:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Funcionario funcionario;
     private String nombreUsuario;
     private String clave;
     private String tipoUsuario;

    public Usuario() {
    }

    public Usuario(BigDecimal idUsuario, Funcionario funcionario, String nombreUsuario, String clave, String tipoUsuario) {
       this.idUsuario = idUsuario;
       this.funcionario = funcionario;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.tipoUsuario = tipoUsuario;
    }
   
    public Usuario(Funcionario funcionario, String nombreUsuario, String clave, String tipoUsuario) {
       this.funcionario = funcionario;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.tipoUsuario = tipoUsuario;
    }
    
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


